apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jira
  title: jira
  description: jira
spec:
  owner: user:guest
  type: user
  parameters:
    - title: Project Issues Jira
      required:
        # - issuetype
        # - project
        - typDesMA
      properties:
        # project:
        #   title: project
        #   type: string
        #   ui:autofocus: true
        #   enum:
        #     - 'MMG Mitarbeiter- und Rechteverwaltung (MURV)'
        # issuetype:
        #   title: issuetype
        #   type: string
        #   enum:
        #     - 'Stammdaten'
        typDesMA:
          title: Typ des MA 
          enum:
            - 'Arbeitnehmeruberlassung'
            - 'Dienstleister'
            - 'LH-Group Mitarbeiter'
            - 'Mitarbeiter'
            - 'Praktikant'
            - 'Werkstudent'

    - title: Standart User data
      properties:
        userObject:
          title: User Info
          type: object
          required: 
            - vorgang
            # - firstName
            # - lastName
            # - costCenter
            # - startOfWork
            # - department
          properties: 
            vorgang:
              title: Vorgang
              enum:
                - 'Aufbau / Anlage / Einrichtung'
                - 'Auderung'
                - 'Abbau / Ruckbau / Loschen'
            # firstName:
            #   title: Vorname(Firstname)
            #   type: string
            # lastName:
            #   title: Nachname(Lastname)
            #   type: string
            # email:
            #   title: Email Address
            #   type: string
            # costCenter:
            #   title: Kostenstelle(Cost center)
            #   type: string
            # startOfWork:
            #   title: Arbeitsbeginn(Start of work)
            #   type: string
            #   format: date
            # department:
            #   title: Department(Abteilung)
            #   type: string
            #   enum:
            #     - 'AQ/LS'
            #     - 'BER M/BR-A'
    
    - title: Extra User Info
      dependencies:
        typDesMA:
          allOf:
            - if:
                properties:
                  typDesMA:
                    anyOf:
                      - const: Dienstleister
                      - const: Praktikant
              then:
                properties:
                  lastName:
                    title: Last Name
                    type: string
                required:
                  - lastName
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}