apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jira-issue-create
  title: Create an issue in Jira
  description: t
spec:
  owner: user:guest
  type: user
  parameters:
    - title: Fill in some steps
      properties:
        includeName:
          title: Include Name?
          type: boolean
          default: true

      dependencies:
        includeName:
          allOf:
            - if:
                properties:
                  includeName:
                    const: true
              then:
                properties:
                  lastName:
                    title: Last Name
                    type: string
                # You can use additional fields of parameters within conditional parameters such as required.
                required:
                  - lastName
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}