apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jira
  title: jira
  description: jira
spec:
  owner: user:guest
  type: user
  parameters:
    - title: Project Issues Jira
      required:
        # - issuetype
        # - project
        - typDesMA
      properties:
        # project:
        #   title: project
        #   type: string
        #   ui:autofocus: true
        #   enum:
        #     - 'MMG Mitarbeiter- und Rechteverwaltung (MURV)'
        # issuetype:
        #   title: issuetype
        #   type: string
        #   enum:
        #     - 'Stammdaten'
        typDesMA:
          title: Typ des MA 
          enum:
            - 'Arbeitnehmeruberlassung'
            - 'Dienstleister'
            - 'LH-Group Mitarbeiter'
            - 'Mitarbeiter'
            - 'Praktikant'
            - 'Werkstudent'

    - title: Standart User data
      properties:
        userObject:
          title: User Info
          type: object
          required: 
            - vorgang
            # - firstName
            # - lastName
            # - costCenter
            # - startOfWork
            # - department
          properties: 
            vorgang:
              title: Vorgang
              enum:
                - 'Aufbau / Anlage / Einrichtung'
                - 'Auderung'
                - 'Abbau / Ruckbau / Loschen'
            # firstName:
            #   title: Vorname(Firstname)
            #   type: string
            # lastName:
            #   title: Nachname(Lastname)
            #   type: string
            # email:
            #   title: Email Address
            #   type: string
            # costCenter:
            #   title: Kostenstelle(Cost center)
            #   type: string
            # startOfWork:
            #   title: Arbeitsbeginn(Start of work)
            #   type: string
            #   format: date
            # department:
            #   title: Department(Abteilung)
            #   type: string
            #   enum:
            #     - 'AQ/LS'
            #     - 'BER M/BR-A'
    
    - title: Extra User Info
      dependencies:
        typDesMA:
          allOf:
 # ----  uNumber
            # - if:
            #     properties:
            #       typDesMA:
            #         anyOf:
            #           - const: Arbeitnehmeruberlassung
            #           - const: LH-Group Mitarbeiter
            #           - const: Mitarbeiter
            #           - const: Praktikant
            #           - const: Werkstudent
            #   then:
            #     properties:
            #       uNumber:
            #         title: uNumber
            #         type: string
            #     required:
            #       - uNumber

 # ----  endDate + vorgesetzter
            # - if:
            #     properties:
            #       typDesMA:
            #         anyOf:
            #           - const: Arbeitnehmeruberlassung
            #           - const: Mitarbeiter
            #           - const: Praktikant
            #           - const: Werkstudent
            #   then:
            #     properties:
            #       endDate:
            #         title: End date
            #         type: string
            #       vorgesetzter:
            #         title: Vorgesetzter
            #         type: string
            #     required:
            #       - endDate
            #       - vorgesetzter

 # ----  mmgVerantwortlicher

            - if:
                properties:
                  typDesMA:
                    anyOf:
                      - const: Dienstleister
                      - const: LH-Group Mitarbeiter
              then:
                required:
                  - mmgVerantwortlicher
                properties:
                  mmgVerantwortlicher:
                    title: MMG-Verantwortlicher
                    type: string
            - if:
                properties:
                  typDesMA:
                    anyOf:
                      - const: Mitarbeiter
                      - const: LH-Group Mitarbeiter
              then:
                required:
                  - titel
                properties:
                  titel:
                    title: Titel
                    type: string
            - if:
                properties:
                  typDesMA:
                    anyOf:
                      - const: Arbeitnehmeruberlassung
              then:
                required:
                  # - externalFirm
                  - buLhGroup
                  # - compAddres
                  # - telephone
                  # - emailAdd
                  - mobile
                  - hardware
                properties:
                  # externalFirm:
                  #   title: Externe Firma
                  #   type: string
                  buLhGroup:
                    title: BU der LH-Group?
                    type: boolean
                    ui:widget: radio
                  # compAddres:
                  #   title: Copany Adres/Firmenanschrift
                  #   type: string
                  # telephone:
                  #   title: Telephone number (company/external employee)//Telefonnummer (Firma/Externer MA)
                  #   type: string
                  # emailAdd:
                  #   title: Email address (company/external employee)//Email Adresse (Firma/Externer MA)
                  #   type: string
                  mobile:
                    title: Mobiltelefon
                    type: boolean
                    ui:widget: radio
                  hardware:
                    title: hardware
                    type: string
                    enum:
                      - 'Neu'
                      - 'Vorhanden'
                      - 'Nicht erforderlich'
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}