apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jira
  title: jira
  description: jira
spec:
  owner: user:guest
  type: user
  parameters:
    - title: Project Issues Jira
      required:
        # - issuetype
        # - project
        - typDesMA
      properties:
        # project:
        #   title: project
        #   type: string
        #   ui:autofocus: true
        #   enum:
        #     - 'MMG Mitarbeiter- und Rechteverwaltung (MURV)'
        # issuetype:
        #   title: issuetype
        #   type: string
        #   enum:
        #     - 'Stammdaten'
        typDesMA:
          title: Typ des MA 
          enum:
            - 'Arbeitnehmeruberlassung'
            - 'Dienstleister'
            - 'LH-Group Mitarbeiter'
            - 'Mitarbeiter'
            - 'Praktikant'
            - 'Werkstudent'

    - title: User Info
      dependencies:
        typDesMA:
          allOf:
            - if:
                properties:
                  typDesMA:
                    anyOf:
                      - const: Dienstleister
                      - const: Praktikant
              then:
                properties:
                  lastName:
                    title: Last Name
                    type: string
                required:
                  - lastName
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}