apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jira-issue-create
  title: Create an issue in Jira
  description: t
spec:
  owner: user:guest
  type: user
  parameters:
    - title: Fill in some steps
      properties:
        typDesMA:
          title: Typ des MA 
          enum:
            - 'Arbeitnehmeruberlassung'
            - 'Dienstleister'
            - 'LH-Group Mitarbeiter'
            - 'Mitarbeiter'
            - 'Praktikant'
            - 'Werkstudent'
      dependencies:
        typDesMA:
          allOf:
            - if:
                properties:
                  typDesMA:
                    anyOf:
                      - const: Dienstleister
                      - const: Praktikant
              then:
                properties:
                  lastName:
                    title: Last Name
                    type: string
                # You can use additional fields of parameters within conditional parameters such as required.
                required:
                  - lastName
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}