apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lino
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: http://backstage.io
  annotations:
    github.com/project-slug: backstage/backstage
    lighthouse.com/website-url: https://backstage.io
    jira/project-key: backstage
    jira/token-type: Bearer # optional, used for Activity stream feed. If you are using Basic auth you can skip this.
    jira/label: backstage # optional, refine filter based on a label or labels (CSV)
spec:
  type: library
  owner: CNCF
  lifecycle: production
