apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jira-issue-create
  title: Create an issue in Jira
  description: t
spec:
  owner: user:guest
  type: user
  parameters:
    - title: Project Issues Jira
      required:
        - issuetype
        - project
        - typDesMA
      properties:
        project:
          title: project
          type: string
          ui:autofocus: true
          enum:
            - 'MMG Mitarbeiter- und Rechteverwaltung (MURV)'
        issuetype:
          title: issuetype
          type: string
          enum:
            - 'Stammdaten'
        typDesMA:
          title: Typ des MA 
          enum:
            - 'Arbeitnehmeruberlassung'
            - 'Dienstleister'
            - 'LH-Group Mitarbeiter'
            - 'Mitarbeiter'
            - 'Praktikant'
            - 'Werkstudent'    
    - title: Standart User data 
      properties:
        userObject:
          title: User Info
          type: object
          required: 
            - vorgang
            - firstName
            - lastName
            - costCenter
            - startOfWork
            - department
          properties: 
            vorgang:
              title: Vorgang
              enum:
                - 'Aufbau / Anlage / Einrichtung'
                - 'Auderung'
                - 'Abbau / Ruckbau / Loschen'
            firstName:
              title: Vorname(Firstname)
              type: string
            lastName:
              title: Nachname(Lastname)
              type: string
            email:
              title: Email Address
              type: string
            costCenter:
              title: Kostenstelle(Cost center)
              type: string
            startOfWork:
              title: Arbeitsbeginn(Start of work)
              type: string
              format: date
            department:
              title: Department(Abteilung)
              type: string
              enum:
                - 'AQ/LS'
                - 'BER M/BR-A'
    - title: Additional Information for Option Arbeitnehmeruberlassung
      # if: '{{ parameters.typDesMA === "optionA" || parameters.typDesMA === "optionB" }}' # Conditional logic
      if: '{{ parameters.typDesMA != "Dienstleister" }}' # Conditional logic
      required:
        - uNumber
      properties:
        uNumber:
            title: U-Number
            type: string
        # mmgManager:
        #   title: MMG-Verantwortlicher
        #   type: string
        # title:
        #   title: Title
        #   type: string
        # isCompanyChanger:
        #   title: Is a company changer?
        #   type: string
        #   enum:
        #     - 'Yes'
        #     - 'No'
        # buLhGroup:
        #   title: BU der LH-Group?
        #   type: string
        #   enum:
        #     - 'Yes'
        #     - 'No'
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
  #   - id: jira
  #     name: jira pub
  #     action: jira:issue:create
  #     input:
  #       project: ${{ parameters.project }}
  #       summary: ${{ parameters.summary }}
  #       issuetype: ${{ parameters.issuetype }}
  #       description: ${{ parameters.description }}
  #       userObject: ${{ parameters.userObject }}

  # # Outputs are displayed to the user after a successful execution of the template.
  # output:
  #   links:
  #     - title: Repository
  #       url: ${{ steps['publish'].output.remoteUrl }}
  #     - title: Open in catalog
  #       icon: catalog
  #       entityRef: ${{ steps['register'].output.entityRef }}
