apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: testttt
  title: t
  description: t
spec:
  owner: user:guest
  type: user
  parameters:
    - title: Fill in some steps
      required:
        - name
        - description
        - summary
        - issuetype
        - project
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
        description:
          title: description
          type: string
        summary:
          title: summary
          type: string
        project:
          title: project
          type: string
          ui:autofocus: true
          enum:
            - BACKSTAGE
        issuetype:
          title: issuetype
          type: string
          enum:
            - '10001'
    - title: User Information
      type: object
      required: 
          - firstName
          - lastName
          - uNumber
          - email
          - costCenter
          - department
          - departmentLong
          - title
          - isCompanyChanger
      properties:  
        firstName:
          title: First Name
          type: string
        lastName:
          title: Last name
          type: string
        uNumber:
          title: U-Number
          type: string
        email:
          title: Email Address
          type: string
        costCenter:
          title: Cost center
          type: string
        department:
          title: Department
          type: string
        departmentLong:
          title: Department (long)
          type: string
          description: Department (long)
        title:
          title: Title
          type: string
        isCompanyChanger:
          title: Is a company changer?
          type: boolean
          ui:widget: radio
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
    - id: jira
      name: jira pub
      action: jira:issue:create
      input:
        project: ${{ parameters.project }}
        summary: ${{ parameters.summary }}
        issuetype: ${{ parameters.issuetype }}
        description: ${{ parameters.description }}
    # - id: publish
    #   name: Publish
    #   action: publish:github:pull-request
    #   input:
    #     description: This is ${{ parameters.name }}
    #     title: This is ${{ parameters.name }}
    #     repoUrl: github.com?repo=backstage-config&owner=lmilt95
    #     repoVisibility: public
    #     branchName: mtest
    #     targetPath: test
    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: https://github.com/lmilt95/backstage-config/tree/mtest/test
    #     catalogInfoPath: '/${{ parameters.name }}-catalog-info.yaml'

  # Outputs are displayed to the user after a successful execution of the template.
  # output:
  #   links:
  #     - title: Repository
  #       url: ${{ steps['publish'].output.remoteUrl }}
  #     - title: Open in catalog
  #       icon: catalog
  #       entityRef: ${{ steps['register'].output.entityRef }}
