apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: register-software
  title: Register New Software
  description: A template to dynamically show and require fields based on user selection.
spec:
  owner: team@example.com
  type: user
  parameters:
    - title: Software Type Selection
      required:
        - softwareType
      properties:
        softwareType:
          type: string
          title: Software Type
          description: Select the type of software to register
          enum:
            - Web Application
            - Library
            - Service

    - title: Web Application Fields
      if: ${{ parameters.softwareType === "Web Application" }}
      properties:
        domainName:
          type: string
          title: Domain Name
          description: Enter the domain name for the web application.
          default: '' # Default value ensures it does not get treated as required unless explicitly handled

        hostingProvider:
          type: string
          title: Hosting Provider
          description: Specify the hosting provider.
          default: ''

    - title: Library Fields
      if: ${{ parameters.softwareType === "Library" }}
      properties:
        repositoryUrl:
          type: string
          title: Repository URL
          description: Provide the GitHub or GitLab repository URL for the library.
          default: ''

    - title: Service Fields
      if: ${{ parameters.softwareType === "Service" }}
      properties:
        apiUrl:
          type: string
          title: API URL
          description: Specify the URL of the service API.
          default: ''

        serviceOwner:
          type: string
          title: Service Owner
          description: Enter the name of the service owner or team.
          default: ''

  steps:
    - id: validate-and-register
      name: Validate and Register Software
      action: custom:validate-and-register
      input:
        softwareType: ${{ parameters.softwareType }}
        domainName: ${{ parameters.domainName }}
        hostingProvider: ${{ parameters.hostingProvider }}
        repositoryUrl: ${{ parameters.repositoryUrl }}
        apiUrl: ${{ parameters.apiUrl }}
        serviceOwner: ${{ parameters.serviceOwner }}
