apiVersion: backstage.io/v1beta1
kind: User
metadata:
  namespace: default
  name: U714208
  description: Sebastian Fecher

spec:
  profile:
    displayName: Sebastian Fecher
    email: Sebastian.Fecher@milesandmore.com
  memberOf: []
