apiVersion: backstage.io/v1beta1
kind: User
metadata:
  namespace: default
  name: u123456
  description: sdgs sdg d

spec:
  profile:
    displayName: sdgdf sgsdfg d
    email: dfggdffdgr@dfgdfgfdg.com
  memberOf: []
